# Generated by Django 4.2.15 on 2026-05-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0009_set_horaires_cabinet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileattente',
            name='priorite',
            field=models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('control', 'Contrôle')], default='normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='rendez_vous',
            name='priority',
            field=models.CharField(choices=[('normal', 'Cas ordinaire'), ('urgent', 'Urgent'), ('control', 'Contrôle')], default='normal', max_length=10),
        ),
    ]
