# Generated by Django 4.2.15 on 2026-05-31 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rdv', '0010_alter_fileattente_priorite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionChatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_action', models.CharField(default='redirect', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('url_cible', models.URLField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Action Chatbot',
                'verbose_name_plural': 'Actions Chatbot',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('sujet', models.CharField(blank=True, default='', max_length=200)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('fermee', 'Fermée'), ('transferee', 'Transférée à un agent')], default='active', max_length=20)),
                ('contexte', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rdv_conversation',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQDentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, unique=True)),
                ('reponse', models.TextField()),
                ('categorie', models.CharField(blank=True, default='general', max_length=100)),
                ('mots_cles', models.CharField(blank=True, default='', help_text='Mots-clés séparés par des virgules', max_length=500)),
                ('priorite', models.IntegerField(default=0, help_text="Ordre d'affichage (0 = normal, plus haut = prioritaire)")),
                ('compteur_utilisation', models.PositiveIntegerField(default=0, help_text='Nombre de fois que cette FAQ a été utilisée')),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'FAQ Dentaire',
                'verbose_name_plural': 'FAQs Dentaires',
                'ordering': ['-priorite', 'question'],
            },
        ),
        migrations.CreateModel(
            name='MessageChatbot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'Utilisateur'), ('assistant', 'Assistant IA'), ('system', 'Système'), ('agent', 'Agent humain')], max_length=10)),
                ('contenu', models.TextField()),
                ('intention_detectee', models.CharField(blank=True, default='', max_length=50)),
                ('confiance', models.FloatField(default=0.0)),
                ('sources_utilisees', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='rdv.conversation')),
            ],
            options={
                'db_table': 'rdv_message_chatbot',
                'ordering': ['created_at'],
            },
        ),
    ]
