"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.2.
"""

from pathlib import Path
import os
import socket
import subprocess

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ============================================
# 1. CONFIGURATION DE BASE
# ============================================

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-$fb4#(d^-!4-*84#q81jg15fx&yqtx+)_@*%ek47zu*0oaa#)z')

# DEBUG controle par variable d'environnement
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

# ============================================
# 2. TAILSCALE - DETECTION IP PRIVEE
# ============================================

def get_tailscale_ip():
    """
    Detecte automatiquement l'IP Tailscale (100.x.x.x)
    Retourne None si Tailscale n'est pas connecte
    """
    try:
        result = subprocess.run(['tailscale', 'ip', '-4'], 
                              capture_output=True, text=True, timeout=5)
        if result.returncode == 0:
            ip = result.stdout.strip()
            if ip.startswith('100.'):
                return ip
    except Exception:
        pass
    return None

# Recupere l'IP Tailscale si disponible
TAILSCALE_IP = get_tailscale_ip()

# ============================================
# 3. ALLOWED_HOSTS (Tailscale — machines du tailnet)
# ============================================

# IPs Tailscale du projet (salma, fatima-ezzahra, …)
TAILSCALE_HOSTS = [
    '100.127.77.70',   # salma
    '100.103.204.35',  # fatima-ezzahra
    '100.106.168.124', # a35-de-salma (telephone)
]

ALLOWED_HOSTS = list(TAILSCALE_HOSTS)

# IP de la machine courante si Tailscale est connecte
if TAILSCALE_IP and TAILSCALE_IP not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(TAILSCALE_IP)

_extra = os.environ.get('DJANGO_ALLOWED_HOSTS', '').strip()
if _extra:
    ALLOWED_HOSTS.extend(h.strip() for h in _extra.split(',') if h.strip())

# Accès local (évite CSRF invalid si on alterne localhost / Tailscale)
for _local in ('127.0.0.1', 'localhost', 'testserver'):
    if _local not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(_local)

# ============================================
# 4. CSRF TRUSTED ORIGINS (Tailscale + local)
# ============================================

_csrf = os.environ.get('CSRF_TRUSTED_ORIGINS', '').strip()
CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf.split(',') if o.strip()] if _csrf else []

_all_tailscale_ips = list(dict.fromkeys(TAILSCALE_HOSTS + ([TAILSCALE_IP] if TAILSCALE_IP else [])))
for _ip in _all_tailscale_ips:
    for _origin in (f'http://{_ip}:8000', f'https://{_ip}:8000'):
        if _origin not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(_origin)

# Toutes les origines des hôtes autorisés (port dev 8000)
for _host in ALLOWED_HOSTS:
    if not _host or _host == '*':
        continue
    for _scheme in ('http', 'https'):
        for _origin in (f'{_scheme}://{_host}:8000', f'{_scheme}://{_host}'):
            if _origin not in CSRF_TRUSTED_ORIGINS:
                CSRF_TRUSTED_ORIGINS.append(_origin)

# ============================================
# 5. COOKIES & SECURITE DE BASE
# ============================================

SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = 'Lax'

SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# ============================================
# 6. APPLICATIONS & MIDDLEWARE
# ============================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rdv',
    'rest_framework',
    'corsheaders',
    'axes',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'axes.middleware.AxesMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
    BASE_DIR.parent / 'frontend' / 'templates',
    BASE_DIR.parent / 'frontend' / 'templates' / 'rdv',
],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'rdv.context_processors.user_display_name',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# ============================================
# 7. BASE DE DONNEES
# ============================================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('MYSQL_DATABASE', 'gestion_rdv'),
        'USER': os.environ.get('MYSQL_USER', 'root'),
        'PASSWORD': os.environ.get('MYSQL_PASSWORD', ''),
        'HOST': os.environ.get('MYSQL_HOST', '127.0.0.1'),
        'PORT': os.environ.get('MYSQL_PORT', '3306'),
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8mb4',
        },
        'CONN_MAX_AGE': 600,
    }
}

# ============================================
# 8. AUTHENTIFICATION
# ============================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 8},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# ============================================
# 9. REST FRAMEWORK & JWT
# ============================================

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
}

# ============================================
# 10. CORS
# ============================================

CORS_ALLOWED_ORIGINS = [
    f"http://{ip}:8000" for ip in _all_tailscale_ips
] + [
    f"https://{ip}:8000" for ip in _all_tailscale_ips
]

CORS_ALLOW_CREDENTIALS = True

# ============================================
# 11. INTERNATIONALISATION
# ============================================

LANGUAGE_CODE = 'fr-fr'
TIME_ZONE = 'Africa/Casablanca'
USE_I18N = True
USE_TZ = True
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================
# 12. FICHIERS STATIQUES & MEDIA
# ============================================

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR.parent / 'frontend' / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ============================================
# 13. AUTHENTIFICATION REDIRECTIONS
# ============================================

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/extranet/'
LOGOUT_REDIRECT_URL = '/'
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'webmaster@localhost')
CSRF_FAILURE_VIEW = 'rdv.views.csrf_failure'

# ============================================
# 14. AXES (Protection brute force)
# ============================================

AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 1  # 1 heure
AXES_LOCK_OUT_AT_FAILURE = True
AXES_RESET_ON_SUCCESS = True

# ============================================
# 15. CONFIGURATION HTTPS (CRITIQUE)
# ============================================
# 
# LOGIQUE : 
# - DEBUG=True  -> Local, pas de HTTPS
# - DEBUG=False -> Production, HTTPS force
# - TAILSCALE   -> Reseau prive, HTTPS optionnel
#

if DEBUG:
    # ========== MODE LOCAL (developpement) ==========
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_SSL_REDIRECT = False
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_BROWSER_XSS_FILTER = False
    X_FRAME_OPTIONS = 'SAMEORIGIN'
    
    print("[MODE LOCAL]")
    print("   - DEBUG: True")
    print("   - HTTPS: Desactive")
    if TAILSCALE_IP:
        print(f"   - Tailscale IP (cette machine): {TAILSCALE_IP}")
        print(f"   - URL: http://{TAILSCALE_IP}:8000/")
    print(f"   - ALLOWED_HOSTS: {ALLOWED_HOSTS}")

else:
    # ========== MODE PRODUCTION ==========
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = os.environ.get('DJANGO_SECURE_SSL_REDIRECT', '1') == '1'
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', 31536000))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'
    
    print("[MODE PRODUCTION]")
    print("   - DEBUG: False")
    print("   - HTTPS: Active")

# ============================================
# 16. CONFIGURATION TAILSCALE SPECIFIQUE
# ============================================

# Si Tailscale est detecte et on n'est pas en DEBUG strict
# On peut utiliser un mode "reseau prive" (HTTPS optionnel)
if TAILSCALE_IP and not DEBUG:
    # Mode reseau prive Tailscale : HTTPS recommande mais pas force
    # car Tailscale chiffre deja le trafic (WireGuard)
    SECURE_SSL_REDIRECT = os.environ.get('DJANGO_SECURE_SSL_REDIRECT', '0') == '1'
    
    print("[MODE TAILSCALE]")
    print(f"   - IP: {TAILSCALE_IP}")
    print("   - Chiffrement: WireGuard (Tailscale)")
    print(f"   - HTTPS force: {SECURE_SSL_REDIRECT}")