# Generated by Django 4.2.11 on 2026-02-18 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0003_utilisateur'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rendez_vous',
            options={'ordering': ['-priority', 'date', 'created_at']},
        ),
        migrations.AddField(
            model_name='rendez_vous',
            name='priority',
            field=models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='rendez_vous',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
    ]
