# Generated by Django 6.0.2 on 2026-02-26 23:27

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0005_service_creneauhoraire_rendez_vous_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HoraireCabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.PositiveSmallIntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')])),
                ('heure_ouverture', models.TimeField()),
                ('heure_fermeture', models.TimeField()),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Horaire cabinet',
                'verbose_name_plural': 'Horaires cabinet',
                'ordering': ['jour', 'heure_ouverture'],
            },
        ),
        migrations.CreateModel(
            name='JourFermeture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('motif', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Jour de fermeture',
                'verbose_name_plural': 'Jours de fermeture',
                'ordering': ['date'],
            },
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('agent', 'Agent'), ('user', 'User')], default='user', max_length=10),
        ),
        migrations.CreateModel(
            name='FileAttente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ticket', models.PositiveIntegerField()),
                ('priorite', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('rendez_vous', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='rdv.rendez_vous')),
            ],
            options={
                'verbose_name': "File d'attente",
                'verbose_name_plural': "Files d'attente",
                'ordering': ['-priorite', 'numero_ticket'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
            },
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compte', to='rdv.patient')),
            ],
            options={
                'verbose_name': 'Compte',
                'verbose_name_plural': 'Comptes',
            },
        ),
    ]
