# Generated by Django 6.0.2 on 2026-02-27 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0007_fix_admin_agent_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL image pour la carte "Notre travail"'),
        ),
    ]
